---
- hosts: localhost
  become: yes

  tasks:
    - name: Add keys for repos
      apt_key:
        url: "{{ item }}"
      with_items:
        - https://packages.cloud.google.com/apt/doc/apt-key.gpg
        - https://packages.microsoft.com/keys/microsoft.asc
        - https://download.docker.com/linux/ubuntu/gpg

    - name: Add external repos
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        - deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
        - deb https://apt.kubernetes.io/ kubernetes-xenial main
        - deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

    - name: Remove apps
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - hexlet

    - name: Install required apps
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - atop
        - chromium-browser
        - clipit
        - code
        - docker-ce
        - git
        - gkrellm
        - golang
        - htop
        - iftop
        - iotop
        - fonts-powerline
        - kubectl
        - lnav
        - meld
        - nmap
        - nethogs
        - pep8
        - pylint
        - python-pip
        - screenfetch
        - shellcheck
        - sysstat
        - tilix
        - tmux
        - ttf-mscorefonts-installer
        - vagrant
        - vim
        - virtualbox
        - virtualbox-qt
        - zsh

    - name: Install pip packages
      pip:
        name: bottle
